"""游戏画面用的像素素材:哇鸥、障碍、码头道具。

和 icons.py 一样是可读的字符网格,字符含义见 pal.py。
区别只是尺寸不固定 —— 每张图自带宽高,由 emit.py 编成 js/game/pixels.js。

主角哇鸥的四帧在 WAOU 里,身体不动只换翅膀。
"""

from people import PEOPLE
from stallparts import STALL_PARTS
from stall import STALLS
from cat import CAT
from kitchenware import KITCHENWARE
from shed import SHED
from runway import RUNWAY

# ---------- 哇鸥 32×32 ----------
# 主角。原型是红嘴鸥 —— 每年冬天从西伯利亚飞到滇池越冬的那种,
# 红嘴红脚就是它的招牌。哇鸥是留下来没走的那一只。
#
# 四帧只换翅膀,身体一个像素都不动:重心恒定,扇起来不抖
# (见 sprites/README.md 的锚点约定)。所以这里存的是四张完整帧,
# 不是身体 + 翅膀分开存 —— 分开存等于把「合成」搬到运行时,没必要。

WAOU = {
    'up': [
        "................................",
        "................................",
        "................................",
        "................................",
        "............KKKKKKKK............",
        "..........KKwwwwwwwwKK..........",
        ".........KwwwwwwwwwwwwK.........",
        "........KwwwwwwwwwwwwwwK........",
        ".......KKwwKKwwwwwwKKwwKK.......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        ".....KwwwwKKKwwwwwwKKKwwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        "KKK..KwwwKKKKKwwwwKKKKKwwwK..KKK",
        "KKKKKKwwwKKKKKwwwwKKKKKwwwKKKKKK",
        ".KKKKKwwwKKKKKwwwwKKKKKwwwKKKKK.",
        "..KKKKwwwwKKKwwwwwwKKKwwwwKKKK..",
        "...KKKwwwwwwVVKKKKVVwwwwwwKKK...",
        "....KKwwwwVVVKXXXXKVVVwwwwKK....",
        ".....KKwwVVVVKXXXXKVVVVwwKK.....",
        "......KwwVVVVVKKKKVVVVVwwK......",
        ".......KVVVVVVVVVVVVVVVVK.......",
        "........KVVVVVVVVVVVVVVK........",
        ".........KVVVVVVVVVVVVK.........",
        "..........KKVVVVVVVVKK..........",
        "...........XXXKKKKXXX...........",
        "...........XXX....XXX...........",
        "............X......X............",
        "................................",
        "................................",
        "................................",
    ],
    'mid': [
        "................................",
        "................................",
        "................................",
        "................................",
        "............KKKKKKKK............",
        "..........KKwwwwwwwwKK..........",
        ".........KwwwwwwwwwwwwK.........",
        "........KwwwwwwwwwwwwwwK........",
        ".......KKwwKKwwwwwwKKwwKK.......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        ".....KwwwwKKKwwwwwwKKKwwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwwKKKwwwwwwKKKwwwwK.....",
        "KKKKKKwwwwwwVVKKKKVVwwwwwwKKKKKK",
        "KKKKKKwwwwVVVKXXXXKVVVwwwwKKKKKK",
        ".KKKKKKwwVVVVKXXXXKVVVVwwKKKKKK.",
        "...KKKKwwVVVVVKKKKVVVVVwwKKKK...",
        ".....KKKVVVVVVVVVVVVVVVVKKK.....",
        "........KVVVVVVVVVVVVVVK........",
        ".........KVVVVVVVVVVVVK.........",
        "..........KKVVVVVVVVKK..........",
        "...........XXXKKKKXXX...........",
        "...........XXX....XXX...........",
        "............X......X............",
        "................................",
        "................................",
        "................................",
    ],
    'down': [
        "................................",
        "................................",
        "................................",
        "................................",
        "............KKKKKKKK............",
        "..........KKwwwwwwwwKK..........",
        ".........KwwwwwwwwwwwwK.........",
        "........KwwwwwwwwwwwwwwK........",
        ".......KKwwKKwwwwwwKKwwKK.......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        ".....KwwwwKKKwwwwwwKKKwwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwwKKKwwwwwwKKKwwwwK.....",
        ".....KwwwwwwVVKKKKVVwwwwwwK.....",
        "....KKwwwwVVVKXXXXKVVVwwwwKK....",
        "...KKKKwwVVVVKXXXXKVVVVwwKKKK...",
        "..KKKKKwwVVVVVKKKKVVVVVwwKKKKK..",
        ".KKKKKKKVVVVVVVVVVVVVVVVKKKKKKK.",
        "KKKKK...KVVVVVVVVVVVVVVK...KKKKK",
        "KKK......KVVVVVVVVVVVVK......KKK",
        "..........KKVVVVVVVVKK..........",
        "...........XXXKKKKXXX...........",
        "...........XXX....XXX...........",
        "............X......X............",
        "................................",
        "................................",
        "................................",
    ],
}

# 扇动一个周期:上 → 平 → 下 → 平
WAOU_CYCLE = ['up', 'mid', 'down', 'mid']

def waou_frames():
    return [WAOU[k] for k in WAOU_CYCLE]


# ---------- 障碍 ----------

# 气球 20×30
BALLOON = [
"......KKKK......",
"....KKRRRRKK....",
"...KRRRRRRRRK...",
"..KRRwRRRRRRRK..",
"..KRwRRRRRRRRK..",
".KRRRRRRRRRRRRK.",
".KRRRRRRRRRRRRK.",
".KRRRRRRRRRRRRK.",
".KrRRRRRRRRRRrK.",
"..KrRRRRRRRRrK..",
"..KrrRRRRRRrrK..",
"...KrrRRRRrrK...",
"....KrrrrrrK....",
".....KKrrKK.....",
"......KKKK......",
".......KK.......",
"......KYYK......",
"......KKKK......",
".......KK.......",
".......KK.......",
]

# 风筝 20×24
KITE = [
".......KK.......",
"......KYYK......",
".....KYYYYK.....",
"....KYYYYYYK....",
"...KYYYYYYYYK...",
"..KYYYYYYYYYYK..",
".KYYYYYYYYYYYYK.",
"KKKKKKKKKKKKKKKK",
".KRRRRRRRRRRRRK.",
"..KRRRRRRRRRRK..",
"...KRRRRRRRRK...",
"....KRRRRRRK....",
".....KRRRRK.....",
"......KRRK......",
".......KK.......",
".......K........",
"......K.........",
".....KRK........",
"......K.........",
".......K........",
"......KRK.......",
".......K........",
"................",
"................",
]


# ---------- 码头道具 ----------

# 小吃摊 46×36:中式路边摊。招牌 + 红布围裙 + 铁板上烤着的饵块 + 一摞蒸笼。
# 旧的固定摊子(STAND)删了 —— 摊子现在分四个阶段,见 tools/stall.py


# 木桶 14×16
BARREL = [
"..KKKKKKKK..",
".KdLLLLLLdK.",
"KdLLLLLLLLdK",
"KKKKKKKKKKKK",
"KDDDDDDDDDDK",
"KDLDDDDDDDDK",
"KDLDDDDDDDDK",
"KKKKKKKKKKKK",
"KDDDDDDDDDDK",
"KDLDDDDDDDDK",
"KDDDDDDDDDDK",
"KKKKKKKKKKKK",
"KdddddddddK.",
".KddddddddK.",
".KKKKKKKKKK.",
"............",
]

# 板条箱 14×14
CRATE = [
"KKKKKKKKKKKK",
"KLDDDDDDDDdK",
"KDKKDDDDKKDK",
"KDDKKDDKKDDK",
"KDDDKKKKDDDK",
"KDDDKKKKDDDK",
"KDDKKDDKKDDK",
"KDKKDDDDKKDK",
"KLDDDDDDDDdK",
"KKKKKKKKKKKK",
"............",
"............",
]

# 大坝路灯 10×30:海埂大坝上一排一排的那种,弯脖子灯
# (滇池没有灯塔 —— 原来那座是海边设定留下的)
LAMP = [
"....KKKKK.",
"...KwwwwyK",
"...KwyyyoK",
"...KKKKKK.",
"....KDDK..",
"....KDDK..",
"...KKDDK..",
"..KKDDK...",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
".KKDDKK...",
".KdDDdK...",
".KKKKKK...",
]

# 灯杆比看着需要的长得多 —— 它得高过后面那道水泥栏杆(栏杆顶在甲板上方
# 39 格)。第一版只有 26 格高,灯头正好落在栏杆横杆上,两样东西糊成一团,
# 挪位置也救不回来:那不是位置问题,是高度不够。

# 系缆桩 8×12
BOLLARD = [
".KKKK.",
"KdLLdK",
"KDDDDK",
".KDDK.",
".KDDK.",
".KDDK.",
".KDDK.",
"KDDDDK",
"KdddDK",
"KKKKKK",
]

# ---------- 云 ----------
# 障碍云和天上飘的云是同一批图,画面里不会出现两种云

CLOUD_A = [
"..........KKKKKKKK..........",
".......KKKwwwwwwwwKKK.......",
".....KKwwwwwwwwwwwwwwKK.....",
"..KKKwwwwwwwwwwwwwwwwwwKKK..",
".KwwwwwwwwwwwwwwwwwwwwwwwwK.",
"KwwwwwwwwwwwwwwwwwwwwwwwwwwK",
"KwwwwwwwwwwwwwwwwwwwwwwwwwwK",
"KAAwwwwwwwwwwwwwwwwwwwwwwAAK",
".KAAAAAAAAAAAAAAAAAAAAAAAAK.",
"..KKKKKKKKKKKKKKKKKKKKKKKK..",
]

CLOUD_B = [
"......KKKKKK......",
"...KKKwwwwwwKK....",
".KKwwwwwwwwwwwKK..",
"KwwwwwwwwwwwwwwwK.",
"KwwwwwwwwwwwwwwwK.",
"KAAwwwwwwwwwwwwAK.",
".KAAAAAAAAAAAAAK..",
"..KKKKKKKKKKKKK...",
]

# 小船 26×18:远处海面上的一点戏,顺便给海平线一个参照物
BOAT = [
"..........KK..............",
"..........KwK.............",
"..........KwwK............",
"..........KwwwK...........",
"..........KwwwwK..........",
"..........KwwwwwK.........",
"..........KwwwwwwK........",
"..........KwwwwwwwK.......",
"..........KKKKKKKKK.......",
"..........KK..............",
"KKKKKKKKKKKKKKKKKKKKKKKK..",
"KRRRRRRRRRRRRRRRRRRRRRRK..",
".KrrrrrrrrrrrrrrrrrrrrK...",
"..KKKKKKKKKKKKKKKKKKKK....",
]

# 乌云 22×16:飞行时的障碍。
# 原来障碍用的是天上飘的那朵白云,和背景云长得一样,玩家分不清哪个能撞。
STORM = [
"......KKKKKKKK........",
"...KKKHHHHHHHHKK......",
"..KHHHHHHHHHHHHHK.....",
".KHHHHHHHHHHHHHHHK....",
".KHHKKHHHHHHKKHHHK....",
".KHHKKHHHHHHKKHHHK....",
"KHHHHHHHHHHHHHHHHHK...",
"KHHHHHHKKKKHHHHHHHK...",
"KhhhhhhhhhhhhhhhhhK...",
".KhhhhhhhhhhhhhhhK....",
"..KKKKKKKKKKKKKKK.....",
"....K.......K.........",
"...KBK.....KBK........",
"...KBK.....KBK........",
"....K.......K.........",
]

# ---------- 表演 ----------

# 哇鸥的表演动作,16×16,和 icons.py 里那只同一个身板,只改姿势。
# 三帧:站着 / 张开翅膀 / 鞠躬。站着那帧直接用图标,这里只放另外两个。
WAOU_WING = [
"................",
"....KKKKKKKK....",
"..KKwwwwwwwwKK..",
"..KwwwwwwwwwwK..",
"..KwwKKwwKKwwK..",
"KKKwwKKwwKKwwKKK",
"KwwwwwwwwwwwwwwK",
"KwwwwwwwwwwwwwwK",
".KKwwwKXXKwwwKK.",
"..KwwwwKKwwwwK..",
"..KwwVVVVVVwwK..",
"..KwVVVVVVVVwK..",
"..KwVVVVVVVVwK..",
"...KKVVVVVVKK...",
"....KKKKKKKK....",
".....XX..XX.....",
]

WAOU_BOW = [
"................",
"................",
"................",
"....KKKKKKKK....",
"..KKwwwwwwwwKK..",
"..KwwwwwwwwwwK..",
"..KwKKKKKKKKwK..",
"..KwwwwwwwwwwK..",
"KKKwwwKXXKwwwKKK",
".KKwwwwKKwwwwKK.",
"..KwwVVVVVVwwK..",
"..KwVVVVVVVVwK..",
"...KKVVVVVVKK...",
"....KKKKKKKK....",
".....XX..XX.....",
"................",
]

# 围观的路人。9×24,只做剪影 —— 大坝上人来人往,画清楚反而抢戏。
# 高度是刻意的:得明显高过 16px 的哇鸥,不然一只海鸥和成年人一样高,
# 整个场景的尺度就垮了。
# 围观路人搬去 tools/people.py 了 —— 原来那两个纯灰剪影站一排像一堵墙。

GULL_BIG = [
".....................................................................................................",
".....................................................................................................",
".....................................................................................................",
".....................................................................................................",
".....................................................................................................",
".....................................................................................................",
".....................................................................................................",
".......................................................K.............................................",
"...............................................KKKKKKKKwKKKKKKKK.....................................",
"...........................................KKKKwwwwwwwwwwwwwwwwwKKKK.................................",
"........................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwKKK..............................",
"......................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"....................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................",
"..................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK........................",
".................................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.......................",
"...............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.....................",
"..............................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK....................",
".............................KwwwwwwwwwwwwKKKwwwwwKKKwwwwwwKKKwwwwwwwwwwwwwwwwwwwK...................",
"............................KwwwwwwwwwwwwwKKKwwwwwKKKwwwwwwKKKwwwwwwwwwwwwwwwwwwwwK..................",
"...........................KwwwwwwwwwwwwwwKKKwwwwwKKKwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwK.................",
"..........................KwwwwwwwwwwwwwwwwwKKKwwwKKKwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwK................",
".........................KwwwwwwwwwwwwwwwwwwKKKwwwKKKwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwwK...............",
"........................KwwwwwwwwwwwwwwwwwwwKKKwwwKKKwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwwwK..............",
".......................KwwwwwwwwwwwwwwwwwwwwKKKwwwKKKwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwK.............",
"......................KwwwwwwwwwwwwwwwwwwwwwKKKwwwKKKwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwK............",
".....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...........",
".....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........",
"....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK........",
"....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK......",
"...................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK....",
"...................KwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..",
"..................KwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.",
"..................KwwwwwwwwwwwwwwwwwwwwwwwwwKwwwwwKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".................KwwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".................KwwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"................KwwwwwwwXXXXXXXXwwwwwwwwwwKKKwwwwwKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"................KwwwwwwwXXXXXXXXwwwwwwwwwwKKKwwwwwKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"................KXXXXXXXXXXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"............KKKKKXXXXXXXXXXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".......KKKKKXXXXXXXXXXXXXXXXXXXXwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"......KXXXXXXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...KKKKXXXXXXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..KXXXXXKKKKKKKKKKKKKKKKKKXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..KXXXXXKKKKKKKKKKKKKKKKKKXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..KXXXXXrrrrrrrrrrrrrrrrrXXXXXXXwwwwwwwwwwwKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..KXXXXXrrrrrrrrrrrrrrrrrXXXXXXXwwwwwwwwwwwKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...KKKKXXXXXXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".......KKKKKXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwwwwKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...........KXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwwwwwwKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"............KKKKwwXXXXXXXXXXXXXwwwwwwwwwwwwwwwwwwwKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...............KwwXXXXXXXXXXXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...............KwwwwwwwwwXXXXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVwwwwwwwwwwwwwwwwwwwwwww",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwww",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwww",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwww",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVw",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".............KwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".............KwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".............KwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"..............KwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"..............KwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...............KwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...............KwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"................KwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"................KwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".................KwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".................KwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"..................KwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...................KwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...................KwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"....................KwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".....................KwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"......................KwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".......................KwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".......................KwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"........................KwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".........................KwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"..........................KwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...........................KwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"............................KKwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"..............................KwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...............................KwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"................................KwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".................................KKwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...................................KwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK.",
"....................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK..",
"......................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK....",
"........................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK......",
"..........................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK........",
"............................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK..........",
"..............................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK............",
".................................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK...............",
]

# 万达双塔 38×88。昆明的地标,两座一模一样并排立着 ——
# 对称是它最好认的地方。窗带夜里会点亮。
WANDA = [
".......aaaa................aaaa.......",
".......aaaa................aaaa.......",
".......aaaa................aaaa.......",
".......aaaa................aaaa.......",
".......aaaa................aaaa.......",
".....AAAAAAAA............AAAAAAAA.....",
".....AAAAAAAA............AAAAAAAA.....",
".....AAAAAAAA............AAAAAAAA.....",
".....AAAAAAAA............AAAAAAAA.....",
".....AAAAAAAA............AAAAAAAA.....",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAyyAAyyAAyyAAyyAAyyAAyyAAyyAAyyAAyyAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"......................................",
"......................................",
]

# 石栏杆 26×22,横向可平铺。长虫山观景台上的那种。
RAIL = [
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
]

# ---------- 小屋 ----------

# 草棚里的哇鸥,62×54。近景,要够圆 —— 这是它最放松的样子。
# 比例照 32px 那版等比放大:**眼睛占身宽约四分之一**,这是萌的关键,
# 第一版把眼睛按「大图就该多细节」的想法画小了,出来是个蛋。
HUT_WAOU = [
"..................................................KKKKKKKK.......................................................",
".............................................KKKKKKKKKKKKKKKKKKKKKKK.............................................",
"..........................................KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK........................................",
"......................................KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK....................................",
"...................................KKKKKKKKKKKKKKKKKKwKVVKKKKKKKKKKKKKKKKKKKKKKK.................................",
".................................KKKKKKKKKKKKKKwwwwwwwwVVwwwwwVVwwwwKKKKKKKKKKKKKK...............................",
"...............................KKKKKKKKKKwwwwwwwwwwwwwVVwwwwwwVVwwwwwwwwKKKKKKKKKKKKK............................",
".............................KKKKKKKKKwwwwwwwwwwwwwwwwVVwwwwwwVVVwwwwwwwwwwwwKKKKKKKKKK..........................",
"............................KKKKKKKKwwwwwwwwwwwwwwwwwwVVwwwwwwwVwwwwwwwwwwwwwwwwKKKKKKKK.........................",
".........................KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKK.......................",
"........................KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKK.....................",
".......................KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVwwwwwKKKKKKK....................",
".....................KKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVwwwwwwwKKKKKK...................",
"....................KKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKK..................",
"...................KKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVwwwwKKKKKK.................",
"..................KKKKKKwwwwVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVwwwwVKKKKK................",
".................KKKKKwwwwwwVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVKKKKK...............",
"................KKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVKKKKKK..............",
"...............KKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKK.............",
"..............KKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKK............",
".............KKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKK...........",
"............KKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKK...........",
"............KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKK..........",
"...........KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKK.........",
"...........KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKK........",
"..........KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVwwwKKKK........",
"........KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVwwKKKK........",
"........KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVwwwwwwwwwwwwwwwVwwwwKKKK.......",
".......KKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKwVVKKKVVVwKwwwwwwwwwwwwwwwwwKKKKK......",
".......KKKKwwwwwwwwwwwwwwwwVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKVVKKKVVVKKKwwwwwwwwwwwwwwwwwKKKK......",
"......KKKKwwwwwwwwwwwwwwwwVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKVVKKKKVVKKKKwwwwwwwwwwwwwwwwKKKKK.....",
".....KKKKKwwwwwwwwwwwwwwKKKVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKVVKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKK.....",
".....KKKKwwwwwwwwwwwwKKKKKKKwwwwKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwKKKK....",
".....KKKKwwwwwwwwwwwKKKVVKKKKwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKK....",
"....KKKKwwwwwwwwwwwwKKKVVKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKK....",
"....KKKKwwwwwwwwwwwwwKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwKKKK...",
"...KKKKKwwwwwwwwwwwwwKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVKKKKKKVVVVVVVVVKKKVVVVwwwwwwwwwwwwwwwKKKK...",
"...KKKKwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVKKKVVVVVVVVVVKKKVVVVVwwwwwwwwwwwwwwKKKKK..",
"...KKKKwwwwwwwwwwwwwwKKKKKKKVVVVVKKKKVVwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVKKKVVVVVVVVVKKKKVVVVwwwwwwwwwwwwwwwwKKKK..",
"...KKKKwwwwwwwwwwwwwwKKKKKVVVVVVVVKKKVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVKKKKKVVVVVVVVKKKKVVVVVwwwwwwwwwwwwwwwKKKK..",
"..KKKKKwwwwwwwwwwwwVVVKKKVVVVVVVVVKKKVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVKKKKKKKKVVKKKKKKKVVVVwwwwwwwwwwwwwwwwwKKK..",
"..KKKKwwwwwwwwwwwwwVVVKKKKVVVVVVVVKKKVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVKKKKKKKKKKKKKKKKKVVVVVwwwwwwwwwwwwwwwwKKKK.",
"..KKKKwwwwwwwwwwwwwVVVKKKKKVVVVVVKKKKVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKVVVVwwwwwwwwwwwwwwwwwKKKK.",
"..KKKKwwwwwwwwwwwwwVVVKKKKKKVVKKKKKKKVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKVVVwwwwwwwwwwwwwwwwwwKKKK.",
".KKKKwwwwwwwwwwwwwVVVVVKKKKKKKKKKKKKKKVwwwwwwwwwwwwwwwwVVwwwwwwwwwVwwwKKKKKKKKKKKKKKKKKVVVwwwwwwwwwwwwwwwwwwwKKK.",
".KKKKKwwwwwwwwwwwwVVVVVKKKKKKKKKKKKKKKVVVwwwwwwwwwVVwwwVVwwwwwwwwwVVVVVKKKKKKVVVVVVKKKKVVwwwwwwwwwwwwwwwwwwwwKKKK",
".KKKKwwwwwwwwwwwwwwVVVVVKKKKKKKKKKKKKKVVVVwwwVVwwwVVVVVVVVwwwwwwwVVVVVVKKKKKVVVVVVVVKKKVVVwwwwwwwwwwwwwwwwwwwKKKK",
".KKKKwwwwwwwwwwwwwwwVVVVKKKKKKKKKKKKKKVVVVVwwVVVwVVVVVVVVVVwwwwwwVVVVVVKKKKKVVVVVVVVKKKVVVwwwwwwwwwwwwwwwwwwwKKKV",
".KKKKwwwwwwwwwwwwwwwwVVVKKKKKVVVVVKKKKVVVVVVVVVVVVVKKKKKKKKKKKKKVVVVVVVKKKVVVVVVVVVKKKKKVwwwwwwwwwwwwwwwwwwwwKKKK",
"VKKKKwwwwwwwwwwwwwwwVVVVKKKKVVVVVVVKKKKVVVVVVVVKKKKKKKKKKKKKKKKKKVVVVVVKKKVVVVVVVVVKKKKwwwwwwwwwwwwwwwwwwwwwwKKK.",
"VKKKwwwwwwwwwwwwwwwwVVwwKKKKVVVVVVKKKKKVVVVVVKKKKKKKKKKKKKKKKKKKKKVVVVVKKKVVVVVVVVKKKKKwwwwwwwwwwwwwwwwwwwwwwKKK.",
"KKKKwwwwwwwwwwwwwwwwwwwwwKKKKVKKKKKKKKKVVVVKKKKKKKKKXXXXXXXXKXKKKKKVVVKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwKKK.",
"KKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKVVVVKKKKKXXXXXXXXXXXXXXXKKKKVVVKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKK",
"KKKKwwwwwwwwwwwwwwwwwwwwwVKKKKKKKKKKKKKVVVVKKKKXXXXXXXXXXXXXXXXKKKKVVVKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwKKKK",
"KKKKwwwwwwwwwwwwwwwwwwwwwwVVKKKKKKKwwwwVVVVKKKKXXXXXXXXXXXXXXXKKKKVVwwVVKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKV",
"KKKKwwwVwwwwwwwwwwwwwwwwwwVVwwwwwwwwwwwVVVVKKKKXXXXXXXXXXXXXXXKKKVVVwwVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK",
"KKKKwwwwwwwwwwwwwwwwwwwwwwVVwwwwwwwwwwwVVVVVKKKKXXXXXXXXXXXXXKKKKVVVwVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKV",
"KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVKKKKXXXXXXXXXXXXKKKKVVwwVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK",
"VKKKwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwVVVKKKXXXXXXXXXXXKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK.",
".KKKwwwwwwwwwwwwwwVwwKKKKwwwwwwwwwwwwwwwwwwVVVKKKKXXXXXXXXXXKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK.",
".KKKKwwwwwwwwwwwVVVVVKKKKwwwwwwwwwwwwwwwwwwVVVVKKKXXXXXXXXXKKKKVVwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwKKKK.",
".KKKKwwwwwwwwwwwVVVVVKKKKKwwwwwwwwwwwwwwwwwwVVVKKKKXXXXXXXXKKKKVVVwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwKKKK.",
".KKKKwwwwwwwwwwVVVVVVVKKKVVwwwwwwwwwwwwwwwwwwVVKKKKXXXXXXXKKKKVVVVwwwwwwwwwwwwwwwwwwwwwKKKKKwwwwwwwwwwwVVwwwKKKK.",
"..KKKwwwwwwwwVVVVVVVVKKKKVVwwwwwwwwwwwwwwwwwwVVVKKKKXXXXXXKKKKVVwwwwwwwwwwwwwwwwwwwwwwKKKKKwwwwwwwwwwwwVVwwwKKK..",
"...KKwwwwwwwwVVVVVVKKKKKKKVVwwwwwwwwwwwwwwwwwwVVVKKKKXXXXKKKKKVVwwwwwwwwwwwwwwwwwwwwwKKKKKwwwwwwwwwwwwwwwwwKKKK..",
"...KKKwwwwwVVVVVVVKKKKKKKKVVVVwwwwwwwwwwwwwwwwVVVKKKKXXXXKKKKVVVVwwwwwwwwwwwwwwwwwwVVKKKKKwwwVwwwwwwwwwwwwwKKKK..",
"...KKKwwVVVVVVVVVKKKKKKKKKVVVVwwwwwwwwwwwwwwwwwVVVKKKXXXKKKKKVVVVwwwwwwwwwwwwwwwwwVVVKKKKKKVVVVwwwwwwwwwwwwKKKK..",
"...KKKKVVVVVVVVKKKKKKKKKKKVVVVVwwwwwwwwwwwwwwwwwVVKKKKKKKKKKVVVwwwwwwwwwwwwwwwwwVVVVKKKKKKKVVVVVwwwwwwwwwwKKKKK..",
"....KKKVVVVVVVKKKKKKKKKKKKKVVVVwwwwwwwwwwwwwwwwwwwwKKKKKKKKVVVwwwwwwwwwwwwwwwwwVVVVVKKKKKKKKVVVVwwwwwwwwwwKKKK...",
"....KKKKVVVVVKKKKKKKKKKKKKKVVVwwwwwwwwwwwwwwwwwwwwwKKKKKKKKVwwwwwwwwwwwwwwwwwwVVVVVKKKKKKKKKKVVVVVVwwwwwwKKKKK...",
".....KKKKVVVKKKKKKKKKKKKKKKVVVVwwwwwwwwwwwwwwwwwwwwwKKKKKKVwwwwwwwwwwwwwwwwwwwwVVVVKKKKKKKKKKVVVVVVVVVwwwKKKKK...",
".....KKKKKVKKKKKKKKKKKKKKKKVVVVwwwwwwwwwwwwwwwwwwwwwwKKKKVVwwwwwwwwwwwwwwwwwwwwVVVVKKKKKKKKKKKKVVVVVVVVVKKKKK....",
"......KKKKKKKKKKKKKKKKKKKKKVVVVwwwwwwwwwwwwwwwwwwwwwwwKKVVVVwwwwwwwwwwwwwwwwwwVVVVKKKKKKKKKKKKKVVVVVVVVVKKKKK....",
".....KKKKKKKKKKKKKKKKKKKKKKVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwVVVwwwwwwwwwwwwwwwwwwVVVVKKKKKKKKKKKKKKKVVVVVVKKKKK.....",
".....KKKKKKKKKKKKKKKKKKKKKKKKVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVKKKKKKKKKKKKKKKKVVVVKKKKKKK.....",
"....KKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVKKKKKKKKKKKKKKKKVVKKKKKKKK......",
".....KKKKVKKKKKKKKKKKKKKKKKKKVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVKKKKKKKKKKKKKKKKKKKKKKKKKK......",
".....KKKKVVVKKKKKKKKKKKKKKKVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVKKKKKKKKKKKKKKKKKKKKKKKKKK......",
".....KKKKVVVVVKKKKKKKKKKKKKVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVKKKKKKKKKKKKKKKKKKKKKKKKK.......",
"......KKKKVVVVVVVKKKKKKKKKKVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVKKKKKKKKKKKKKKKKKKKKKKKKK.......",
".......KKKKwwVVVVVVVVKKKKKVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVKKKKKKKKKKKKKKVVVVKKKKKK.......",
".......KKKKwwVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVKKKKKKKKVVVVVVVVKKKKK........",
".......KKKKKVVVVVVVVwwVVVVwVVwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVKKKKK.........",
"........KKKKVVVVVVVVwwwVVwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwVwwwwVVVVVVVVVVVVVKKKKK..........",
".........KKKKVVwVVVwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwVVVVVVVVVVVVKKKK...........",
".........KKKKKwwwVVwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwVVwVVVwwwVVKKKKK...........",
"..........KKKKwwwVVwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwVVwwwVVKKKK............",
"..........KKKKKwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwVVwwwKKKKK.............",
"...........KKKKwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwwKKKKK..............",
"...........KKKKKwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwKKKKKK..............",
"............KKKKKwwwwVVwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwKKKKKK...............",
".............KKKKwwwwVVwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwKKKKKK................",
".............KKKKKwwwwwVwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwKKKKK..................",
"..............KKKKKwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwKKKKK...................",
"...............KKKKKwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwKKKKK....................",
"................KKKKKwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwKKKKKK.....................",
".................KKKKKKwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwKKKKKK......................",
"..................KKKKKKwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwKKKKKK.......................",
"...................KKKKKKwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKKK........................",
"....................KKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKK..........................",
".....................KKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKK...........................",
".......................KKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKKK............................",
"........................KKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKKK..............................",
".........................KKKKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKKKKK...............................",
"...........................KKKKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKKKK.................................",
".............................KKKKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKKK....................................",
"...............................KKKKKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVKKKKKKKKKKK.....................................",
".................................KKKKKKKKKKKKVVVVVVVVVVVVVVKKKKKKKKKKKKKKK.......................................",
]

# 睡着的样子。**从 HUT_IDLE 改出来的**,不是另描一张稿 —— 他给的要求就是
# 「在已有的待机动作上进行绘制」。改的只有两处:睁着的梯子眼换成两道微微右斜的短横、
# 右上支一只举起来的翅膀(白面带描边,参考里那是翅膀内侧)。身子、嘴、肚皮、脚照搬。
# 这张不做动画 —— 他说「睡觉动作不需要动态,只需要右上角几个 zzzz 偶尔飘出」,
# 飘的 Z 由 hut.js 的 drawZzz() 画,和这张图无关。生成:tools/sleepart.py
HUT_SLEEP = [
"....................................................................KKKKKKKKKKKKKKKKKK......................................................................",
"...................................................................KKKKKKKKKKKKKKKKKKKK.....................................................................",
".............................................................KKKKKKKwwwwwwwwwwwwwwwwwwKKKKKKK...............................................................",
"...........................................................KKKKKKKKwwwwwwwwwwwwwwwwwwwwKKKKKKKK.............................................................",
".........................................................KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK...........................................................",
".......................................................KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK.........................................................",
".....................................................KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK.......................................................",
"...................................................KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK.....................................................",
".................................................KKKKVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVKKKK...................................................",
"...............................................KKKKVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVKKKK.................................................",
".............................................KKKKVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVKKKK...............................................",
"............................................KKKVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVKKK..............................................",
"..........................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK............................................",
".........................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK...........................................",
"........................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK................KKKKKKK...................",
".......................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............KKKKKKKKKKKK.................",
"......................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.........KKKKKKKwwwKKKKK................",
".....................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK......KKKKKKwwwwwwwwKKK................",
"....................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK....KKKKKwwwwwwwwwwwKKK...............",
"...................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..KKKKwwwwwwwwwwwwwKKK...............",
"..................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwwwwwwwwwwKK...............",
".................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKwwwwwwwwwwwwwwwwKK...............",
"................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwKK...............",
"...............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwKK...............",
"..............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwKK...............",
".............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwKK...............",
"............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwKKK...............",
"............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwKKK...............",
"...........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwKK................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwKKK................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwwKKK................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwwKKK.................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwKKK.................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwKKK..................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwKKK..................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwKKK...................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwKKKK...................",
".........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwKKK....................",
".........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwKKK.....................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwKKKK.....................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwKKK......................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwwwwwwKKK.......................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwKKKK.......................",
".......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwKKKK........................",
".......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwwwwKKKK.........................",
"......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwwwKKKKKK........................",
"......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwwKKKKwKK........................",
"......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwKKKKKwwKK........................",
"......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwKKKKKwwwKK........................",
".....................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKwwwwKKKwwwwwwwwwwwwwwKKKKwwwwwwKK.......................",
"................KKKKKKKKKwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKwwwwwwwwwwwwKKKKKwwwwwwwKKKKKKKKK................",
".............KKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwKKKKKKwwwwwwwwKKKKKKKKKKKK.............",
"...........KKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwKKKKKKwwwwwwwwwwKKKKKKKKKKKKKK...........",
"..........KKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwKKKKKKKKKKKKKKK..........",
"........KKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKK........",
".......KKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKK.......",
"......KKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKK......",
".....KKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKK.....",
"....KKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKK....",
"...KKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKK...",
"...KKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKXXKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKK...",
"..KKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKXXKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKK..",
"..KKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKK..",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXXXXXXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXXXXXXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
"KKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKK",
"KKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKK",
"KKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKK",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
"..KKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKK..",
"...KKKKKKKKKK........KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK........KKKKKKKKKK...",
"......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK......................",
".......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.........................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................",
".........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK...........................",
".........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK...........................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"...........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.............................",
"............................KKVVVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVKK..............................",
"............................KKVVVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVKK..............................",
".............................KKVVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVKK...............................",
"..............................KKVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVKK................................",
"...............................KKVVVVVVVVVwwwwwwwwwwwwwwVVVVVVVVVVVVwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVwwwwwwwwwwwwwwVVVVVVVVVKK.................................",
"................................KKVVVVVVVVwwwwwwwwwwwwwwVVVVVVVVVVVVwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVwwwwwwwwwwwwwwVVVVVVVVKK..................................",
".................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK...................................",
"..................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK....................................",
"...................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK.....................................",
"....................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK......................................",
".....................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK.......................................",
"......................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK........................................",
"........................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK..........................................",
".........................................KKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKK...........................................",
"...........................................KKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKK.............................................",
".............................................KKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKK...............................................",
"...............................................KKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKK.................................................",
".................................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK...................................................",
"...................................................KKKrrrrrrrrVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVrrrrrrrrKKK.....................................................",
"....................................................KKKrrrrrrrVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVrrrrrrrKKK......................................................",
"......................................................KKrrXXXXKKKKVVVVVVVVVVVVVVVVVVVVVVKKKKXXXXrrKK........................................................",
"......................................................KKrrXXXXKKKVVVVVVVVVVVVVVVVVVVVVVVVKKKXXXXrrKK........................................................",
"......................................................KKXXXXXXXXXXXXXXKKKKKKKKKKKKKKXXXXXXXXXXXXXXKK........................................................",
"......................................................KKXXXXXXXXXXXXXKKKKKKKKKKKKKKKKXXXXXXXXXXXXXKK........................................................",
"......................................................KKXXXXXXXXXXwwKK..............KKwwXXXXXXXXXXKK........................................................",
"......................................................KKKXXXXXXXXXwKKK..............KKKwXXXXXXXXXKKK........................................................",
"........................................................KKKKKKKKKKKK..................KKKKKKKKKKKK..........................................................",
"........................................................KKKKKKKKKKKK..................KKKKKKKKKKKK..........................................................",
]

# 大坝上那间草棚 36×30。远远看是个小棚子,点它就进小屋。
# 画得比周围陈设显眼一点(有门洞、有暖光),不然玩家不会想到那儿能点。
SHACK = [
"..........KKKK..........",
".......KKKddddKKK.......",
"....KKKddddddddddKKK....",
"..KKddddddddddddddddddKK.",
".KddLddLddLddLddLddLddK.",
"KdddddddddddddddddddddddK",
"KKKKKKKKKKKKKKKKKKKKKKKK",
".KDDDDDDDDDDDDDDDDDDDDK.",
".KDDDKKKKKKKKKKDDDDDDDK.",
".KDDKSSSSSSSSSSKDDDDDDK.",
".KDDKSSSSSSSSSSKDDDDDDK.",
".KDDKSSSSSSSSSSKDDDDDDK.",
".KDDKSSSSSSSSSSKDDDDDDK.",
".KDDKSSSSSSSSSSKDDDDDDK.",
".KDDKKKKKKKKKKKKDDDDDDK.",
".KDDDDDDDDDDDDDDDDDDDDK.",
"KKKKKKKKKKKKKKKKKKKKKKKK",
"..KddK............KddK..",
"..KddK............KddK..",
"..KKKK............KKKK..",
]

"""小屋里待机用的身子。原作者给的 2048×2048 像素稿里最舒展的那一帧。

**它真正的分辨率是 78×58**(2048 里一格 22 像素),所以取样按原生格子来、
再整数倍放大成 ×2 —— 按目标尺寸去缩会把每一格切成小数格,边线碎成一团。
细账在 tools/idleart.py 开头。

**身子以中轴对折**:翅膀、脚、肚皮的阴影左右对称;**脸最后才贴**,
所以眼睛照旧留着人家画的不对称。结构对称,表情不对称。

**肚皮那片浅灰的上沿抹平过**:原稿那儿是一道软过渡,点取样之后会变成
一排随机的尖刺(「阴影太尖了」)。按列取上沿、中位数滤一遍再重画。

**描边补齐成一整圈**:点取样让四成的轮廓格子丢了描边(取样点落在描边上就有、
落在旁边的白上就没有),翅膀和身子的接缝更是深色直接切白色。
补法是最老那条 —— 凡是挨着透明的格子一律改成描边色,轮廓一定闭合、厚度恒为一格。

脸是从形象稿搬过来的:原稿这批是哭的(眯眼 + 眼泪 + 张嘴嚎),待机要的是
形象稿那张脸 —— 梯子眼带睫毛 + 红三角小嘴。眼睛比嘴单独缩小一档。

待机的**动作**是另一回事:照的是形象稿那 16 张关键帧逐帧量出来的挤压和起落,
表在 js/game/hut.js 的 `IDLE_POSE` 里。图和动作分开取。
"""

HUT_IDLE = [
"....................................................................KKKKKKKKKKKKKKKKKK......................................................................",
"...................................................................KKKKKKKKKKKKKKKKKKKK.....................................................................",
".............................................................KKKKKKKwwwwwwwwwwwwwwwwwwKKKKKKK...............................................................",
"...........................................................KKKKKKKKwwwwwwwwwwwwwwwwwwwwKKKKKKKK.............................................................",
".........................................................KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK...........................................................",
".......................................................KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK.........................................................",
".....................................................KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK.......................................................",
"...................................................KKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK.....................................................",
".................................................KKKKVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVKKKK...................................................",
"...............................................KKKKVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVKKKK.................................................",
".............................................KKKKVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVKKKK...............................................",
"............................................KKKVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVKKK..............................................",
"..........................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK............................................",
".........................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK...........................................",
"........................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................................",
".......................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.........................................",
"......................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK........................................",
".....................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.......................................",
"....................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK......................................",
"...................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.....................................",
"..................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK....................................",
".................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK...................................",
"................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..................................",
"...............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.................................",
"..............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK................................",
".............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK...............................",
"............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..............................",
"............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..............................",
"...........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwKKKKKKKKKKwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwKKKKKKKKKKwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwKK............................",
".........................KKwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKK...........................",
".........................KKwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKK...........................",
"........................KKwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwKK..........................",
"........................KKwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwKK..........................",
"........................KKwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwKK..........................",
"........................KKwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwKK..........................",
".......................KKwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwKK.........................",
".......................KKwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKK.........................",
"......................KKwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwKK........................",
"......................KKwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwKK........................",
"......................KKwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwKK........................",
"......................KKwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwKK........................",
".....................KKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwKK.......................",
"................KKKKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK................",
".............KKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKK.............",
"...........KKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKK...........",
"..........KKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKK..........",
"........KKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKK........",
".......KKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKK.......",
"......KKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKK......",
".....KKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKK.....",
"....KKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKwwwwwwwwKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKK....",
"...KKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKwwwwwwwwKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKK...",
"...KKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKXXKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKK...",
"..KKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKXXKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKK..",
"..KKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKK..",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXXXXXXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXXXXXXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
"KKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKK",
"KKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKK",
"KKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKK",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
".KKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKK.",
"..KKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKK..",
"...KKKKKKKKKK........KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK........KKKKKKKKKK...",
"......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKK......................",
".......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.........................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKXXXXXXKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................",
"........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................",
".........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKXXKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK...........................",
".........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK...........................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"...........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.............................",
"............................KKVVVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVKK..............................",
"............................KKVVVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVKK..............................",
".............................KKVVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVKK...............................",
"..............................KKVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVKK................................",
"...............................KKVVVVVVVVVwwwwwwwwwwwwwwVVVVVVVVVVVVwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVwwwwwwwwwwwwwwVVVVVVVVVKK.................................",
"................................KKVVVVVVVVwwwwwwwwwwwwwwVVVVVVVVVVVVwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVwwwwwwwwwwwwwwVVVVVVVVKK..................................",
".................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK...................................",
"..................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK....................................",
"...................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK.....................................",
"....................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK......................................",
".....................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK.......................................",
"......................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK........................................",
"........................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK..........................................",
".........................................KKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKK...........................................",
"...........................................KKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKK.............................................",
".............................................KKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKK...............................................",
"...............................................KKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKK.................................................",
".................................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK...................................................",
"...................................................KKKrrrrrrrrVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVrrrrrrrrKKK.....................................................",
"....................................................KKKrrrrrrrVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVrrrrrrrKKK......................................................",
"......................................................KKrrXXXXKKKKVVVVVVVVVVVVVVVVVVVVVVKKKKXXXXrrKK........................................................",
"......................................................KKrrXXXXKKKVVVVVVVVVVVVVVVVVVVVVVVVKKKXXXXrrKK........................................................",
"......................................................KKXXXXXXXXXXXXXXKKKKKKKKKKKKKKXXXXXXXXXXXXXXKK........................................................",
"......................................................KKXXXXXXXXXXXXXKKKKKKKKKKKKKKKKXXXXXXXXXXXXXKK........................................................",
"......................................................KKXXXXXXXXXXwwKK..............KKwwXXXXXXXXXXKK........................................................",
"......................................................KKKXXXXXXXXXwKKK..............KKKwXXXXXXXXXKKK........................................................",
"........................................................KKKKKKKKKKKK..................KKKKKKKKKKKK..........................................................",
"........................................................KKKKKKKKKKKK..................KKKKKKKKKKKK..........................................................",
]

SCENERY = {
    'shack':      SHACK,
    'hut_waou':   HUT_WAOU,
    'hut_idle':   HUT_IDLE,
    'hut_sleep':  HUT_SLEEP,
    'gull_big':   GULL_BIG,
    'wanda':      WANDA,
    'rail':       RAIL,
    'waou_wing':  WAOU_WING,
    'waou_bow':   WAOU_BOW,
    **PEOPLE,          # 四个围观路人,见 tools/people.py
    **STALL_PARTS,     # 摊位的零碎升级件,见 tools/stallparts.py
    **STALLS,          # 摊子本体的四个阶段,见 tools/stall.py
    **CAT,             # 折耳根,见 tools/cat.py
    **KITCHENWARE,     # 出摊那一场案上的四件家什,见 tools/kitchenware.py
    **SHED,            # 小木棚和三把伞,见 tools/shed.py
    **RUNWAY,          # 跑道(建好 / 没建),见 tools/runway.py
    'storm':      STORM,
    'boat':       BOAT,
    'cloud_a':    CLOUD_A,
    'cloud_b':    CLOUD_B,
    'balloon':    BALLOON,
    'kite':       KITE,
    'barrel':     BARREL,
    'crate':      CRATE,
    'lamp':       LAMP,
    'bollard':    BOLLARD,
}

def _pad(grid):
    """补齐成矩形,并裁掉四周整行整列的空白。

    手写网格右边漏几个点很常见,与其数格子不如补齐;
    裁空白则是因为这些图是按「底边贴地」或「中心对齐」摆的,
    留一圈空行会让东西凭空浮在半空(海鸥、摊子都栽过)。
    """
    w = max(len(r) for r in grid)
    g = [r + '.' * (w - len(r)) for r in grid]
    while g and set(g[0]) == {'.'}: g.pop(0)
    while g and set(g[-1]) == {'.'}: g.pop()
    left = min(len(r) - len(r.lstrip('.')) for r in g)
    right = min(len(r) - len(r.rstrip('.')) for r in g)
    return [r[left:len(r) - right] for r in g]

SCENERY = {k: _pad(v) for k, v in SCENERY.items()}


