"""游戏画面用的像素素材:哇鸥、障碍、码头道具。

和 icons.py 一样是可读的字符网格,字符含义见 pal.py。
区别只是尺寸不固定 —— 每张图自带宽高,由 emit.py 编成 js/game/pixels.js。

主角哇鸥的四帧在 WAOU 里,身体不动只换翅膀。
"""

from people import PEOPLE
from stallparts import STALL_PARTS

# ---------- 哇鸥 32×32 ----------
# 主角。原型是红嘴鸥 —— 每年冬天从西伯利亚飞到滇池越冬的那种,
# 红嘴红脚就是它的招牌。哇鸥是留下来没走的那一只。
#
# 四帧只换翅膀,身体一个像素都不动:重心恒定,扇起来不抖
# (见 sprites/README.md 的锚点约定)。所以这里存的是四张完整帧,
# 不是身体 + 翅膀分开存 —— 分开存等于把「合成」搬到运行时,没必要。

WAOU = {
    'up': [
        "................................",
        "................................",
        "................................",
        "................................",
        "............KKKKKKKK............",
        "..........KKwwwwwwwwKK..........",
        ".........KwwwwwwwwwwwwK.........",
        "........KwwwwwwwwwwwwwwK........",
        ".......KKwwKKwwwwwwKKwwKK.......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        ".....KwwwwKKKwwwwwwKKKwwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        "KKK..KwwwKKKKKwwwwKKKKKwwwK..KKK",
        "KKKKKKwwwKKKKKwwwwKKKKKwwwKKKKKK",
        ".KKKKKwwwKKKKKwwwwKKKKKwwwKKKKK.",
        "..KKKKwwwwKKKwwwwwwKKKwwwwKKKK..",
        "...KKKwwwwwwVVKKKKVVwwwwwwKKK...",
        "....KKwwwwVVVKXXXXKVVVwwwwKK....",
        ".....KKwwVVVVKXXXXKVVVVwwKK.....",
        "......KwwVVVVVKKKKVVVVVwwK......",
        ".......KVVVVVVVVVVVVVVVVK.......",
        "........KVVVVVVVVVVVVVVK........",
        ".........KVVVVVVVVVVVVK.........",
        "..........KKVVVVVVVVKK..........",
        "...........XXXKKKKXXX...........",
        "...........XXX....XXX...........",
        "............X......X............",
        "................................",
        "................................",
        "................................",
    ],
    'mid': [
        "................................",
        "................................",
        "................................",
        "................................",
        "............KKKKKKKK............",
        "..........KKwwwwwwwwKK..........",
        ".........KwwwwwwwwwwwwK.........",
        "........KwwwwwwwwwwwwwwK........",
        ".......KKwwKKwwwwwwKKwwKK.......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        ".....KwwwwKKKwwwwwwKKKwwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwwKKKwwwwwwKKKwwwwK.....",
        "KKKKKKwwwwwwVVKKKKVVwwwwwwKKKKKK",
        "KKKKKKwwwwVVVKXXXXKVVVwwwwKKKKKK",
        ".KKKKKKwwVVVVKXXXXKVVVVwwKKKKKK.",
        "...KKKKwwVVVVVKKKKVVVVVwwKKKK...",
        ".....KKKVVVVVVVVVVVVVVVVKKK.....",
        "........KVVVVVVVVVVVVVVK........",
        ".........KVVVVVVVVVVVVK.........",
        "..........KKVVVVVVVVKK..........",
        "...........XXXKKKKXXX...........",
        "...........XXX....XXX...........",
        "............X......X............",
        "................................",
        "................................",
        "................................",
    ],
    'down': [
        "................................",
        "................................",
        "................................",
        "................................",
        "............KKKKKKKK............",
        "..........KKwwwwwwwwKK..........",
        ".........KwwwwwwwwwwwwK.........",
        "........KwwwwwwwwwwwwwwK........",
        ".......KKwwKKwwwwwwKKwwKK.......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        "......KwwKwKwKwwwwKwKwKwwK......",
        ".....KwwwwKKKwwwwwwKKKwwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        ".....KwwwKwwKKwwwwKwwKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwKKKKKwwwwKKKKKwwwK.....",
        ".....KwwwwKKKwwwwwwKKKwwwwK.....",
        ".....KwwwwwwVVKKKKVVwwwwwwK.....",
        "....KKwwwwVVVKXXXXKVVVwwwwKK....",
        "...KKKKwwVVVVKXXXXKVVVVwwKKKK...",
        "..KKKKKwwVVVVVKKKKVVVVVwwKKKKK..",
        ".KKKKKKKVVVVVVVVVVVVVVVVKKKKKKK.",
        "KKKKK...KVVVVVVVVVVVVVVK...KKKKK",
        "KKK......KVVVVVVVVVVVVK......KKK",
        "..........KKVVVVVVVVKK..........",
        "...........XXXKKKKXXX...........",
        "...........XXX....XXX...........",
        "............X......X............",
        "................................",
        "................................",
        "................................",
    ],
}

# 扇动一个周期:上 → 平 → 下 → 平
WAOU_CYCLE = ['up', 'mid', 'down', 'mid']

def waou_frames():
    return [WAOU[k] for k in WAOU_CYCLE]


# ---------- 障碍 ----------

# 气球 20×30
BALLOON = [
"......KKKK......",
"....KKRRRRKK....",
"...KRRRRRRRRK...",
"..KRRwRRRRRRRK..",
"..KRwRRRRRRRRK..",
".KRRRRRRRRRRRRK.",
".KRRRRRRRRRRRRK.",
".KRRRRRRRRRRRRK.",
".KrRRRRRRRRRRrK.",
"..KrRRRRRRRRrK..",
"..KrrRRRRRRrrK..",
"...KrrRRRRrrK...",
"....KrrrrrrK....",
".....KKrrKK.....",
"......KKKK......",
".......KK.......",
"......KYYK......",
"......KKKK......",
".......KK.......",
".......KK.......",
]

# 风筝 20×24
KITE = [
".......KK.......",
"......KYYK......",
".....KYYYYK.....",
"....KYYYYYYK....",
"...KYYYYYYYYK...",
"..KYYYYYYYYYYK..",
".KYYYYYYYYYYYYK.",
"KKKKKKKKKKKKKKKK",
".KRRRRRRRRRRRRK.",
"..KRRRRRRRRRRK..",
"...KRRRRRRRRK...",
"....KRRRRRRK....",
".....KRRRRK.....",
"......KRRK......",
".......KK.......",
".......K........",
"......K.........",
".....KRK........",
"......K.........",
".......K........",
"......KRK.......",
".......K........",
"................",
"................",
]


# ---------- 码头道具 ----------

# 小吃摊 46×36:中式路边摊。招牌 + 红布围裙 + 铁板上烤着的饵块 + 一摞蒸笼。
# 原来那个是西式条纹雨棚,和滇池对不上。
STAND = [
"................KKKKKKKKKKKKKK................",     # 招牌
"................KSSSSSSSSSSSSK................",
"................KSKKSSKKSSKKSK................",
"................KSKKSSKKSSKKSK................",
"................KSSSSSSSSSSSSK................",
"................KKKKKKKKKKKKKK................",
"..................K......K....................",     # 吊绳
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",     # 棚顶
"KDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDK",
"KdddddddddddddddddddddddddddddddddddddddddddK.",
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
".K.........................................K..",     # 立柱
".K...KKKKKK.....KKKKKKKKKKKK.....KKKK......K..",     # 蒸笼 / 铁板
".K...KLLLLK.....KAAAAAAAAAAK.....KEEK......K..",
".K...KKKKKK.....KAtTTTTTTtAK.....KKKK......K..",
".K...KLLLLK.....KAAAAAAAAAAK.....KEEK......K..",
".K...KKKKKK.....KKKKKKKKKKKK.....KKKK......K..",
".K.........................................K..",
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",     # 台面
"KLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLK",
"KDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDK",
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
"KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK",     # 红布围裙
"KXXwwXXXXXXXXwwXXXXXXXXXwwXXXXXXXXwwXXXXXXXXK",
"KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK",
"KrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrK",
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
"..KDDK..............................KDDK.....",     # 腿
"..KDDK..............................KDDK.....",
"..KddK..............................KddK.....",
"..KKKK..............................KKKK.....",
]

# 木桶 14×16
BARREL = [
"..KKKKKKKK..",
".KdLLLLLLdK.",
"KdLLLLLLLLdK",
"KKKKKKKKKKKK",
"KDDDDDDDDDDK",
"KDLDDDDDDDDK",
"KDLDDDDDDDDK",
"KKKKKKKKKKKK",
"KDDDDDDDDDDK",
"KDLDDDDDDDDK",
"KDDDDDDDDDDK",
"KKKKKKKKKKKK",
"KdddddddddK.",
".KddddddddK.",
".KKKKKKKKKK.",
"............",
]

# 板条箱 14×14
CRATE = [
"KKKKKKKKKKKK",
"KLDDDDDDDDdK",
"KDKKDDDDKKDK",
"KDDKKDDKKDDK",
"KDDDKKKKDDDK",
"KDDDKKKKDDDK",
"KDDKKDDKKDDK",
"KDKKDDDDKKDK",
"KLDDDDDDDDdK",
"KKKKKKKKKKKK",
"............",
"............",
]

# 大坝路灯 10×30:海埂大坝上一排一排的那种,弯脖子灯
# (滇池没有灯塔 —— 原来那座是海边设定留下的)
LAMP = [
"....KKKKK.",
"...KwwwwyK",
"...KwyyyoK",
"...KKKKKK.",
"....KDDK..",
"....KDDK..",
"...KKDDK..",
"..KKDDK...",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
"..KDDK....",
".KKDDKK...",
".KdDDdK...",
".KKKKKK...",
]

# 灯杆比看着需要的长得多 —— 它得高过后面那道水泥栏杆(栏杆顶在甲板上方
# 39 格)。第一版只有 26 格高,灯头正好落在栏杆横杆上,两样东西糊成一团,
# 挪位置也救不回来:那不是位置问题,是高度不够。

# 系缆桩 8×12
BOLLARD = [
".KKKK.",
"KdLLdK",
"KDDDDK",
".KDDK.",
".KDDK.",
".KDDK.",
".KDDK.",
"KDDDDK",
"KdddDK",
"KKKKKK",
]

# ---------- 云 ----------
# 障碍云和天上飘的云是同一批图,画面里不会出现两种云

CLOUD_A = [
"..........KKKKKKKK..........",
".......KKKwwwwwwwwKKK.......",
".....KKwwwwwwwwwwwwwwKK.....",
"..KKKwwwwwwwwwwwwwwwwwwKKK..",
".KwwwwwwwwwwwwwwwwwwwwwwwwK.",
"KwwwwwwwwwwwwwwwwwwwwwwwwwwK",
"KwwwwwwwwwwwwwwwwwwwwwwwwwwK",
"KAAwwwwwwwwwwwwwwwwwwwwwwAAK",
".KAAAAAAAAAAAAAAAAAAAAAAAAK.",
"..KKKKKKKKKKKKKKKKKKKKKKKK..",
]

CLOUD_B = [
"......KKKKKK......",
"...KKKwwwwwwKK....",
".KKwwwwwwwwwwwKK..",
"KwwwwwwwwwwwwwwwK.",
"KwwwwwwwwwwwwwwwK.",
"KAAwwwwwwwwwwwwAK.",
".KAAAAAAAAAAAAAK..",
"..KKKKKKKKKKKKK...",
]

# 小船 26×18:远处海面上的一点戏,顺便给海平线一个参照物
BOAT = [
"..........KK..............",
"..........KwK.............",
"..........KwwK............",
"..........KwwwK...........",
"..........KwwwwK..........",
"..........KwwwwwK.........",
"..........KwwwwwwK........",
"..........KwwwwwwwK.......",
"..........KKKKKKKKK.......",
"..........KK..............",
"KKKKKKKKKKKKKKKKKKKKKKKK..",
"KRRRRRRRRRRRRRRRRRRRRRRK..",
".KrrrrrrrrrrrrrrrrrrrrK...",
"..KKKKKKKKKKKKKKKKKKKK....",
]

# 乌云 22×16:飞行时的障碍。
# 原来障碍用的是天上飘的那朵白云,和背景云长得一样,玩家分不清哪个能撞。
STORM = [
"......KKKKKKKK........",
"...KKKHHHHHHHHKK......",
"..KHHHHHHHHHHHHHK.....",
".KHHHHHHHHHHHHHHHK....",
".KHHKKHHHHHHKKHHHK....",
".KHHKKHHHHHHKKHHHK....",
"KHHHHHHHHHHHHHHHHHK...",
"KHHHHHHKKKKHHHHHHHK...",
"KhhhhhhhhhhhhhhhhhK...",
".KhhhhhhhhhhhhhhhK....",
"..KKKKKKKKKKKKKKK.....",
"....K.......K.........",
"...KBK.....KBK........",
"...KBK.....KBK........",
"....K.......K.........",
]

# ---------- 表演 ----------

# 哇鸥的表演动作,16×16,和 icons.py 里那只同一个身板,只改姿势。
# 三帧:站着 / 张开翅膀 / 鞠躬。站着那帧直接用图标,这里只放另外两个。
WAOU_WING = [
"................",
"....KKKKKKKK....",
"..KKwwwwwwwwKK..",
"..KwwwwwwwwwwK..",
"..KwwKKwwKKwwK..",
"KKKwwKKwwKKwwKKK",
"KwwwwwwwwwwwwwwK",
"KwwwwwwwwwwwwwwK",
".KKwwwKXXKwwwKK.",
"..KwwwwKKwwwwK..",
"..KwwVVVVVVwwK..",
"..KwVVVVVVVVwK..",
"..KwVVVVVVVVwK..",
"...KKVVVVVVKK...",
"....KKKKKKKK....",
".....XX..XX.....",
]

WAOU_BOW = [
"................",
"................",
"................",
"....KKKKKKKK....",
"..KKwwwwwwwwKK..",
"..KwwwwwwwwwwK..",
"..KwKKKKKKKKwK..",
"..KwwwwwwwwwwK..",
"KKKwwwKXXKwwwKKK",
".KKwwwwKKwwwwKK.",
"..KwwVVVVVVwwK..",
"..KwVVVVVVVVwK..",
"...KKVVVVVVKK...",
"....KKKKKKKK....",
".....XX..XX.....",
"................",
]

# 围观的路人。9×24,只做剪影 —— 大坝上人来人往,画清楚反而抢戏。
# 高度是刻意的:得明显高过 16px 的哇鸥,不然一只海鸥和成年人一样高,
# 整个场景的尺度就垮了。
# 围观路人搬去 tools/people.py 了 —— 原来那两个纯灰剪影站一排像一堵墙。

GULL_BIG = [
".....................................................................................................",
".....................................................................................................",
".....................................................................................................",
".....................................................................................................",
".....................................................................................................",
".....................................................................................................",
".....................................................................................................",
".......................................................K.............................................",
"...............................................KKKKKKKKwKKKKKKKK.....................................",
"...........................................KKKKwwwwwwwwwwwwwwwwwKKKK.................................",
"........................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwKKK..............................",
"......................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"....................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........................",
"..................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK........................",
".................................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.......................",
"...............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.....................",
"..............................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK....................",
".............................KwwwwwwwwwwwwKKKwwwwwKKKwwwwwwKKKwwwwwwwwwwwwwwwwwwwK...................",
"............................KwwwwwwwwwwwwwKKKwwwwwKKKwwwwwwKKKwwwwwwwwwwwwwwwwwwwwK..................",
"...........................KwwwwwwwwwwwwwwKKKwwwwwKKKwwwwwwKKKwwwwwwwwwwwwwwwwwwwwwK.................",
"..........................KwwwwwwwwwwwwwwwwwKKKwwwKKKwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwK................",
".........................KwwwwwwwwwwwwwwwwwwKKKwwwKKKwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwwK...............",
"........................KwwwwwwwwwwwwwwwwwwwKKKwwwKKKwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwwwK..............",
".......................KwwwwwwwwwwwwwwwwwwwwKKKwwwKKKwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwK.............",
"......................KwwwwwwwwwwwwwwwwwwwwwKKKwwwKKKwwwwKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwK............",
".....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...........",
".....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..........",
"....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK........",
"....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK......",
"...................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK....",
"...................KwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..",
"..................KwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.",
"..................KwwwwwwwwwwwwwwwwwwwwwwwwwKwwwwwKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".................KwwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".................KwwwwwwwwwwwwwwwwwwwwwwwwwKKwwwwwKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"................KwwwwwwwXXXXXXXXwwwwwwwwwwKKKwwwwwKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"................KwwwwwwwXXXXXXXXwwwwwwwwwwKKKwwwwwKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"................KXXXXXXXXXXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"............KKKKKXXXXXXXXXXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".......KKKKKXXXXXXXXXXXXXXXXXXXXwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"......KXXXXXXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...KKKKXXXXXXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..KXXXXXKKKKKKKKKKKKKKKKKKXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..KXXXXXKKKKKKKKKKKKKKKKKKXXXXXXwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..KXXXXXrrrrrrrrrrrrrrrrrXXXXXXXwwwwwwwwwwwKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..KXXXXXrrrrrrrrrrrrrrrrrXXXXXXXwwwwwwwwwwwKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...KKKKXXXXXXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".......KKKKKXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwwwwKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...........KXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwwwwwwKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"............KKKKwwXXXXXXXXXXXXXwwwwwwwwwwwwwwwwwwwKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...............KwwXXXXXXXXXXXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...............KwwwwwwwwwXXXXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"............Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"...........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
".........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........Kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVwwwwwwwwwwwwwwwwwwwwwww",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwww",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwww",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwww",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVw",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".............KwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".............KwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".............KwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"..............KwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"..............KwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...............KwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...............KwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"................KwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"................KwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".................KwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".................KwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"..................KwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...................KwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...................KwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"....................KwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".....................KwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"......................KwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".......................KwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".......................KwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"........................KwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".........................KwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"..........................KwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...........................KwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"............................KKwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"..............................KwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...............................KwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"................................KwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
".................................KKwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"...................................KwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK.",
"....................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK..",
"......................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK....",
"........................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK......",
"..........................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK........",
"............................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK..........",
"..............................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK............",
".................................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK...............",
]

# 万达双塔 38×88。昆明的地标,两座一模一样并排立着 ——
# 对称是它最好认的地方。窗带夜里会点亮。
WANDA = [
".......aaaa................aaaa.......",
".......aaaa................aaaa.......",
".......aaaa................aaaa.......",
".......aaaa................aaaa.......",
".......aaaa................aaaa.......",
".....AAAAAAAA............AAAAAAAA.....",
".....AAAAAAAA............AAAAAAAA.....",
".....AAAAAAAA............AAAAAAAA.....",
".....AAAAAAAA............AAAAAAAA.....",
".....AAAAAAAA............AAAAAAAA.....",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwyyyyyyyyaaa......wwwyyyyyyyyaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"..wwwAAAAAAAAaaa......wwwAAAAAAAAaaa..",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAyyAAyyAAyyAAyyAAyyAAyyAAyyAAyyAAyyAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"......................................",
"......................................",
]

# 石栏杆 26×22,横向可平铺。长虫山观景台上的那种。
RAIL = [
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
"...wwAAaa.....wwAAaa.....wwAAa",
]

# ---------- 小屋 ----------

# 草棚里的哇鸥,62×54。近景,要够圆 —— 这是它最放松的样子。
# 比例照 32px 那版等比放大:**眼睛占身宽约四分之一**,这是萌的关键,
# 第一版把眼睛按「大图就该多细节」的想法画小了,出来是个蛋。
HUT_WAOU = [
"............................................................................................................................",
"............................................................................................................................",
"............................................................................................................................",
"............................................................................................................................",
"............................................................................................................................",
"............................................................................................................................",
"............................................................................................................................",
".............................................................K..............................................................",
"...................................................KKKKKKKKKKwKKKKKKKKKK....................................................",
"..............................................KKKKKwwwwwwwwwwwwwwwwwwwwwKKKKK...............................................",
"...........................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK............................................",
"........................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK.........................................",
"......................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.......................................",
"...................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK....................................",
".................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..................................",
"................................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.................................",
"..............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK...............................",
".............................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..............................",
"...........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...........................",
".........................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..........................",
".......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK........................",
"......................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.......................",
".....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK......................",
"....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.....................",
"...................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK....................",
"..................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...................",
".................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..................",
".................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..................",
"................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.................",
"...............KwwwwwwwwwwwwwwKKKKwwwwwwKKKKwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwKKKKwwwwwwKKKKwwwwwwwwwwwK................",
"..............KwwwwwwwwwwwwwwwKKKKwwwwwwKKKKwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwKKKKwwwwwwKKKKwwwwwwwwwwwwK...............",
"..............KwwwwwwwwwwwwwwwKKKKwwwwwwKKKKwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwKKKKwwwwwwKKKKwwwwwwwwwwwwK...............",
".............KwwwwwwwwwwwwwwwwKKKKwwwwwwKKKKwwKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKwwKKKKwwwwwwKKKKwwwwwwwwwwwwwK..............",
".............KwwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwK..............",
"............KwwwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwK.............",
"...........KwwwwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwwK............",
"...........KwwwwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwwK............",
"..........KwwwwwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwKKKKwwwwKKKKwwwwwwwwwwwwwwwwwwK...........",
"..........KwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKwwwKKKKwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKwwwKKKKwwwwwwwwwwwwwwwwwwK...........",
"..........KwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwK...........",
".........KwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwK..........",
".........KwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwK..........",
".........KwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwK..........",
"........KwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwK.........",
"........KwwwwwwwwwwwwwwwwwwwwKKKKKwwwwwwKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKwwwwwwKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwK.........",
"........KwwwwwwwwwwwwwwwwwwwwKKKKKwwwwwwKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKwwwwwwKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwK.........",
".......KwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwK........",
".KKKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwKKKKKK...",
".KKKKKKKwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwKKKKKK...",
".KKKKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKK...",
".KKKKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKK...",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKK.KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKK",
"KKKKKKK.KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKK",
"KKKKKKK.KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKK",
"KKKKKKK..KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.KKKKKKKKK",
"KKKKKKK..KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwXXXXXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.KKKKKKKKK",
"KKKKKKK..KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwXXXXXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.KKKKKKKKK",
".KKKKKK...KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVXXXXKKKKKKKKKKKKKKKKKKKKKKKKXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..KKKKKK...",
".KKKKKK...KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVXXXXKKKKKKKKKKKKKKKKKKKKKKKKXXXXVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..KKKKKK...",
".KKKKKK...KwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVXXXXXXrrrrrrrrrrrrrrrrrrrrXXXXXXVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..KKKKKK...",
".KKKKKK....KwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVXXXXXXrrrrrrrrrrrrrrrrrrrrXXXXXXVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwK...KKKKKK...",
"...........KwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVXXXXXXXXXXXXXXXXXXXXXXXXVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwK............",
"............KwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVXXXXXXXXXXXXXXXXXXXXXXXXVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwwwwwK.............",
".............KwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwwK..............",
".............KwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwK..............",
"..............KwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwK...............",
"..............KwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwK...............",
"...............KwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwK................",
"................KwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwK.................",
".................KwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwK..................",
".................KwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwK..................",
"..................KwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwK...................",
"...................KwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwK....................",
"....................KwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwK.....................",
".....................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK......................",
"......................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK.......................",
".......................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK........................",
".........................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK..........................",
"..........................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK...........................",
"...........................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK............................",
".............................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK..............................",
"..............................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK...............................",
"................................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK.................................",
".................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK..................................",
"...................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK....................................",
"......................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK.......................................",
"........................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK.........................................",
"...........................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK............................................",
"..............................................KKKKKVVVVVVVVVVVVVVVVVVVVVKKKKK...............................................",
"...................................................KKKKKKKKKKVKKKKKKKKKK....................................................",
".............................................................K..............................................................",
"............................................................................................................................",
"............................................................................................................................",
]

# 睡着的样子。闭眼画成上弯的弧 —— 画成两道横杠会变成生气的眉毛。
HUT_SLEEP = [
"............................................................................................................................",
"............................................................................................................................",
"............................................................................................................................",
"............................................................................................................................",
"............................................................................................................................",
"............................................................................................................................",
"............................................................................................................................",
".............................................................K..............................................................",
"...................................................KKKKKKKKKKwKKKKKKKKKK....................................................",
"..............................................KKKKKwwwwwwwwwwwwwwwwwwwwwKKKKK...............................................",
"...........................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK............................................",
"........................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK.........................................",
"......................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK.......................................",
"...................................KKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKK....................................",
".................................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK..................................",
"................................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.................................",
"..............................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK...............................",
".............................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..............................",
"...........................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK............................",
"..........................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...........................",
".........................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..........................",
".......................KKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKK........................",
"......................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.......................",
".....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK......................",
"....................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.....................",
"...................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK....................",
"..................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...................",
".................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..................",
".................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..................",
"................KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.................",
"...............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK................",
"..............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...............",
"..............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...............",
".............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..............",
".............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..............",
"............KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.............",
"...........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK............",
"...........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK............",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...........",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...........",
"..........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK...........",
".........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..........",
".........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..........",
".........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..........",
"........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.........",
"........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.........",
"........KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.........",
".......KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwK........",
".......KwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKwwwwwwKKKKKKwwwwwwwwwwwwwwwwwwwwwwwK........",
".KKKKKKwwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKK...",
".KKKKKKKwwwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwKKKKwwwwwwwwwwwwwwwwwwwwwKKKKKK...",
".KKKKKKKwwwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwwwwKKKKKK...",
".KKKKKKKwwwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwKKwwwwwwwwwwwwwwwwwwwwwKKKKKK...",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKKKwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKK",
"KKKKKKK.KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKK",
"KKKKKKK.KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKK",
"KKKKKKK.KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwKKKKKKKKKK",
"KKKKKKK..KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.KKKKKKKKK",
"KKKKKKK..KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwXXXXXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.KKKKKKKKK",
"KKKKKKK..KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwXXXXXXXXXXXXXXXXXXXXXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK.KKKKKKKKK",
".KKKKKK...KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVXXXXKKKKKKKKKKKKKKKKKKKKKKKKXXXXwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..KKKKKK...",
".KKKKKK...KwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVXXXXKKKKKKKKKKKKKKKKKKKKKKKKXXXXVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..KKKKKK...",
".KKKKKK...KwwwwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVXXXXXXrrrrrrrrrrrrrrrrrrrrXXXXXXVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwwwwK..KKKKKK...",
".KKKKKK....KwwwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVXXXXXXrrrrrrrrrrrrrrrrrrrrXXXXXXVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwwwK...KKKKKK...",
"...........KwwwwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVXXXXXXXXXXXXXXXXXXXXXXXXVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwwwwwwwwK............",
"............KwwwwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVXXXXXXXXXXXXXXXXXXXXXXXXVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwwwwwK.............",
".............KwwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwwK..............",
".............KwwwwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwwwwK..............",
"..............KwwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwwK...............",
"..............KwwwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwwwK...............",
"...............KwwwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwwwK................",
"................KwwwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwwwK.................",
".................KwwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwwK..................",
".................KwwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwwK..................",
"..................KwwwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwwwK...................",
"...................KwwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwwK....................",
"....................KwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVwK.....................",
".....................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK......................",
"......................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK.......................",
".......................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK........................",
".........................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK..........................",
"..........................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK...........................",
"...........................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK............................",
".............................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK..............................",
"..............................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK...............................",
"................................KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK.................................",
".................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK..................................",
"...................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK....................................",
"......................................KKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKK.......................................",
"........................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK.........................................",
"...........................................KKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKK............................................",
"..............................................KKKKKVVVVVVVVVVVVVVVVVVVVVKKKKK...............................................",
"...................................................KKKKKKKKKKVKKKKKKKKKK....................................................",
".............................................................K..............................................................",
"............................................................................................................................",
"............................................................................................................................",
]

# 大坝上那间草棚 36×30。远远看是个小棚子,点它就进小屋。
# 画得比周围陈设显眼一点(有门洞、有暖光),不然玩家不会想到那儿能点。
SHACK = [
"..........KKKK..........",
".......KKKddddKKK.......",
"....KKKddddddddddKKK....",
"..KKddddddddddddddddddKK.",
".KddLddLddLddLddLddLddK.",
"KdddddddddddddddddddddddK",
"KKKKKKKKKKKKKKKKKKKKKKKK",
".KDDDDDDDDDDDDDDDDDDDDK.",
".KDDDKKKKKKKKKKDDDDDDDK.",
".KDDKSSSSSSSSSSKDDDDDDK.",
".KDDKSSSSSSSSSSKDDDDDDK.",
".KDDKSSSSSSSSSSKDDDDDDK.",
".KDDKSSSSSSSSSSKDDDDDDK.",
".KDDKSSSSSSSSSSKDDDDDDK.",
".KDDKKKKKKKKKKKKDDDDDDK.",
".KDDDDDDDDDDDDDDDDDDDDK.",
"KKKKKKKKKKKKKKKKKKKKKKKK",
"..KddK............KddK..",
"..KddK............KddK..",
"..KKKK............KKKK..",
]

SCENERY = {
    'shack':      SHACK,
    'hut_waou':   HUT_WAOU,
    'hut_sleep':  HUT_SLEEP,
    'gull_big':   GULL_BIG,
    'wanda':      WANDA,
    'rail':       RAIL,
    'waou_wing':  WAOU_WING,
    'waou_bow':   WAOU_BOW,
    **PEOPLE,          # 四个围观路人,见 tools/people.py
    **STALL_PARTS,     # 摊位的升级件,见 tools/stallparts.py
    'storm':      STORM,
    'boat':       BOAT,
    'cloud_a':    CLOUD_A,
    'cloud_b':    CLOUD_B,
    'balloon':    BALLOON,
    'kite':       KITE,
    'stand':      STAND,
    'barrel':     BARREL,
    'crate':      CRATE,
    'lamp':       LAMP,
    'bollard':    BOLLARD,
}

def _pad(grid):
    """补齐成矩形,并裁掉四周整行整列的空白。

    手写网格右边漏几个点很常见,与其数格子不如补齐;
    裁空白则是因为这些图是按「底边贴地」或「中心对齐」摆的,
    留一圈空行会让东西凭空浮在半空(海鸥、摊子都栽过)。
    """
    w = max(len(r) for r in grid)
    g = [r + '.' * (w - len(r)) for r in grid]
    while g and set(g[0]) == {'.'}: g.pop(0)
    while g and set(g[-1]) == {'.'}: g.pop()
    left = min(len(r) - len(r.lstrip('.')) for r in g)
    right = min(len(r) - len(r.rstrip('.')) for r in g)
    return [r[left:len(r) - right] for r in g]

SCENERY = {k: _pad(v) for k, v in SCENERY.items()}


